apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: rtf-converter
build:
  artifacts:
    - image: rtf-converter
      custom:
        buildCommand: ./build.sh
manifests:
  rawYaml:
    - docker/deployment.yaml
