apiVersion: v1
kind: Service
metadata:
  name: rtf-converter
  labels:
    app: rtf-converter
spec:
  ports:
  - port: 20080
    protocol: TCP
  clusterIP: None
  selector:
    app: rtf-converter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rtf-converter
  labels:
    app: rtf-converter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rtf-converter
  template:
    metadata:
      labels:
        app: rtf-converter
    spec:
      containers:
      - name: rtf-converter
        image: rtf-converter
